#!/bin/bash
# =============================================================================
# Version Information Module
# =============================================================================
# Version: 2.0.0 (commit: auto-populated at runtime)
# Last Modified: 2026-01-23
# Source: https://github.com/aradanmn/MinecraftSplitscreenSteamdeck
#
# This module provides version constants and repository information used
# throughout the installer and generated scripts.
# =============================================================================

# Script version - update this when making releases
readonly SCRIPT_VERSION="2.0.0"

# Repository information - change REPO_BRANCH for different branches
readonly REPO_OWNER="aradanmn"
readonly REPO_NAME="MinecraftSplitscreenSteamdeck"
readonly REPO_BRANCH="dev/autogenerated-launcher"  # Change to "main" for release

# Derived URLs
readonly REPO_URL="https://github.com/${REPO_OWNER}/${REPO_NAME}"
readonly REPO_RAW_URL="https://raw.githubusercontent.com/${REPO_OWNER}/${REPO_NAME}/${REPO_BRANCH}"
readonly REPO_MODULES_URL="${REPO_RAW_URL}/modules"

# =============================================================================
# Version Utility Functions
# =============================================================================

# Get the current git commit hash (short form)
# Returns "unknown" if not in a git repository or git is unavailable
get_commit_hash() {
    if command -v git >/dev/null 2>&1; then
        git rev-parse --short HEAD 2>/dev/null || echo "unknown"
    else
        echo "unknown"
    fi
}

# Get the current timestamp in ISO 8601 format
get_timestamp() {
    date -Iseconds 2>/dev/null || date "+%Y-%m-%dT%H:%M:%S%z"
}

# Generate a version header block for scripts
# Arguments:
#   $1 = Script name (e.g., "minecraftSplitscreen.sh")
#   $2 = Description (e.g., "Minecraft Splitscreen Launcher")
generate_version_header() {
    local script_name="${1:-unknown}"
    local description="${2:-Auto-generated script}"
    local commit_hash
    local timestamp

    commit_hash=$(get_commit_hash)
    timestamp=$(get_timestamp)

    cat << EOF
# =============================================================================
# ${description}
# =============================================================================
# Version: ${SCRIPT_VERSION} (commit: ${commit_hash})
# Generated: ${timestamp}
# Generator: install-minecraft-splitscreen.sh v${SCRIPT_VERSION}
# Source: ${REPO_URL}
#
# DO NOT EDIT - This file is auto-generated by the installer.
# To update, re-run the installer script.
# =============================================================================
EOF
}

# Print version information to stdout
print_version_info() {
    local commit_hash
    commit_hash=$(get_commit_hash)

    echo "Minecraft Splitscreen Installer"
    echo "Version: ${SCRIPT_VERSION} (commit: ${commit_hash})"
    echo "Repository: ${REPO_URL}"
    echo "Branch: ${REPO_BRANCH}"
}

# Check if running from the expected repository/branch
# Returns 0 if matches, 1 otherwise
verify_repo_source() {
    if ! command -v git >/dev/null 2>&1; then
        # Can't verify without git, assume OK
        return 0
    fi

    local remote_url
    remote_url=$(git config --get remote.origin.url 2>/dev/null || echo "")

    if [[ -z "$remote_url" ]]; then
        # Not a git repo, running from downloaded script
        return 0
    fi

    # Check if remote contains our repo
    if echo "$remote_url" | grep -qi "${REPO_OWNER}/${REPO_NAME}"; then
        return 0
    fi

    # Different repo - warn but don't fail
    echo "[Warning] Running from a different repository: $remote_url" >&2
    echo "[Warning] Expected: ${REPO_URL}" >&2
    return 1
}
