#!/bin/bash
# =============================================================================
# Minecraft Splitscreen Launcher for Steam Deck & Linux
# =============================================================================
# Version: 5.0.0
#
# This file is auto-generated by the installer (launcher_script_generator.sh).
# The committed copy is a stub. Run the installer to generate the real launcher.
#
# To regenerate:
#   ./install-minecraft-splitscreen.sh
#
# The generated launcher is installed to:
#   ~/.local/share/PolyMC/minecraftSplitscreen.sh
# =============================================================================

echo "This is a stub. Run the installer to generate the real launcher script." >&2
echo "  ./install-minecraft-splitscreen.sh" >&2
exit 1
